sudo: false
language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
env:
  matrix:
    - TOX_ENV=py34-django111
    - TOX_ENV=py35-django111
    - TOX_ENV=py36-django111
install:
  - pip install tox
  - pip install "coverage>=3.7.1" coveralls
script: tox -e $TOX_ENV
after_success:
  - coverage report
  - coveralls
